# Generated by Django 4.1 on 2022-09-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=96)),
                ('last_name', models.CharField(max_length=96)),
                ('email', models.CharField(max_length=96)),
                ('main_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('main_account_holder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=32)),
                ('year', models.CharField(max_length=4)),
                ('tag_state', models.CharField(max_length=32)),
                ('tag_no', models.CharField(max_length=12)),
                ('nick_name', models.CharField(max_length=128)),
                ('engine_type', models.CharField(max_length=32)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='customer.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_interval_in_miles', models.IntegerField()),
                ('reminder_interval_value', models.IntegerField()),
                ('reminder_interval_units', models.CharField(max_length=25)),
                ('last_mileage_serviced', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize_payment_id', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
