# Generated by Django 4.1 on 2022-09-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=25, null=True)),
                ('completion_time_in_mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(max_length=256)),
                ('transaction_date_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('is_asap_request', models.BooleanField(default=False)),
                ('labor_hours', models.IntegerField()),
                ('total_labor_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gratuity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tech_notes', models.CharField(max_length=1000)),
                ('customer_notes', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('customer_vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.vehicle')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.payment')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.type')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.CharField(blank=True, max_length=2560, null=True)),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('part_description', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=50)),
                ('pried_at', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.type')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.type')),
            ],
        ),
    ]
